# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19a3QzOZMHGzCnMGm6v_7Kit3LqOxGNHY
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(layout="wide")
# 
# st.title('South End Transportation Analysis')
# 
# # Load the data
# @st.cache_data
# def load_data():
#     df = pd.read_csv('south_end_transportation_analysis.csv')
#     return df
# 
# df = load_data()
# 
# st.subheader('Overview of Transportation by Age Group')
# 
# # Display the dataframe (optional)
# st.write('Data Sample:', df.head())
# 
# # Create a bar chart for 'Total' transportation by 'Age_Group'
# fig = px.bar(
#     df,
#     x='Age_Group',
#     y='Total',
#     title='Total Transportation by Age Group in South End',
#     labels={'Age_Group': 'Age Group', 'Total': 'Total Transportation (%)'},
#     hover_data={'Total': ':.2f'}
# )
# 
# fig.update_layout(xaxis_title='Age Group', yaxis_title='Total Transportation (%)')
# st.plotly_chart(fig, use_container_width=True)
# 
# st.markdown("""
# ### Explanation:
# - This app loads the `south_end_transportation_analysis.csv` file.
# - It then displays a bar chart showing the 'Total' transportation percentage for each 'Age_Group'.
# - You can modify the `plotly.express` function to create different types of charts or analyze other columns.
# """)